spring.application.name=wallet-service
# 1. Configuración de la conexión a la base de datos H2
spring.datasource.url=jdbc:h2:mem:walletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# ddl-auto=update hace la magia: lee tu @Entity y crea la tabla automáticamente si no existe
spring.jpa.hibernate.ddl-auto=update
# Esto te mostrará en la consola el SQL real que Hibernate está generando por debajo
spring.jpa.show-sql=true

# 3. Habilitar la consola web de H2 para que puedas ver tus datos gráficamente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console